#!/usr/bin/env bash

if [ ! -f "$HOME/.fytoken" ]; then
 . fylogin
fi

export FYTOKEN=$(cat $HOME/.fytoken)

URI=${API_URI:-https://api.fletaloya.com}

STATUS=$(curl --write-out %{http_code} --silent --output /dev/null "$URI/me?authorization=$FYTOKEN")

if [[ "$STATUS" -ne "200" ]]; then
    . fyrefresh
fi
