#!/bin/sh

if [ ! -f "$HOME/.fytoken" ]; then
eif
 . fylogin
fi

export FYTOKEN=$(cat $HOME/.fytoken)

STATUS=$(curl --write-out %{http_code} --silent --output /dev/null "api.fletaloya.com/me?authorization=$FYTOKEN")

if [[ "$STATUS" -ne "200" ]]; then
    . fyrefresh
fi
