#!/usr/bin/env bash

NICKNAME=$1

if test -z $NICKNAME; then
    echo "Debe especificar un nickname"
    exit -1
fi

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

curl -s -X GET "$URI/users/$NICKNAME?authorization=$FYTOKEN"|jq '.last_known_location'
