#!/usr/bin/env bash

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

request=$1
nick=$2

if "all" = "$nick" ]; then
for n in $(curl -s -X GET "$URI/request/$request/availability?authorization=$FYTOKEN"|jq -r '.shippers[].nickname')
 do
 fynewoffer OM6cL0YnMEpY6CImGghQm1NJ80givxEXvtNv90fFAWI $n
 done

else

user=$(curl -s -X GET "$URI/users/$nick?authorization=$FYTOKEN"|jq -r '.id')
shippers=$(curl -s -X GET "$URI/request/$request/availability?authorization=$FYTOKEN"|jq '.shippers')

availability=$(echo $shippers|jq '.|length')

#if [ $availability -ge 1 ]

#Check if shipper exists in available list

shipper=$(echo $shippers|jq '.[]|select(.id=="'$user'")')

body='{"request_id":"'$request'","shippers":{"'$user'":'$shipper'}}'

offer=$(curl -s -X POST -d "$body" "$URI/offers?authorization=$FYTOKEN"|jq -r '.offers_ids[]')

echo "Nueva oferta enviada al Shipper $nick: $offer"

echo "Próximos pasos:"
echo "Monitoree la oferta: fyshowoffer $offer"

#then
#    echo "No hay shippers disponibles en este momento, vuelva a intentarlo mas tarde: fyrequestavailability $request"
#fi

fi
