#!/usr/bin/env bash

#TODO print usage

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

origin=$1
destination=$2
description=$3
sender=$4
receiver=$5
vehicle=$6

case $vehicle in
  "moto")
    vehicle_category=0
    ;;
  "auto")
    vehicle_category=1
    ;;
  "miniflete")
    vehicle_category=2
    ;;
  *)
    vehicle_category=2
    ;;
esac

# replace spaces for + in origin & destination
origin=$(echo "$origin" | sed 's/\ /+/g')
destination=$(echo "$destination" | sed 's/\ /+/g')

address1=$(curl -s -X GET "$URI/geocode?address=$origin"|jq '.address')
addressLine1=$(echo $address1|jq -r '.formatted_address')
latitude1=$(echo $address1|jq '.latitude')
longitude1=$(echo $address1|jq '.longitude')

address2=$(curl -s -X GET "$URI/geocode?address=$destination"|jq '.address')
addressLine2=$(echo $address2|jq -r '.formatted_address')
latitude2=$(echo $address2|jq '.latitude')
longitude2=$(echo $address2|jq '.longitude')

price=$(fyprice "$origin" "$destination" "$vehicle")

zone1=$(curl -s -X GET "$URI/zones/$latitude1/$longitude1"|jq -r '.zone')
zone2=$(curl -s -X GET "$URI/zones/$latitude2/$longitude2"|jq -r '.zone')

availability=$(curl -s -X GET "$URI/shippers?zones=$zone1,$zone2"|jq '.shippers|length')

route=$(curl -s -X GET "$URI/route?points=$latitude1,$longitude1,$latitude2,$longitude2")

distance=$(echo $route|jq -r '.distance')
sla=$(echo $route|jq -r '.commitment')
#TODO: esto tiene que resolverse en el backend, al resolver el `/route`
sla=$(($sla + 1800))

base=$(echo $price|jq '.price.base_price.value')
extras=$(echo $price|jq '.price.price_components[]|select(.description=="Total")|.value')

total=$(($base + $extras))

echo "Pedido: $description - desde: $addressLine1 - hasta: $addressLine2 - precio: \$$total - distancia: $(($distance/1000))Kms - Tiempo sugerido: $(($sla/60)) mins - $availability Shippers disponibles."

read -p "¿Confirma el pedido? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Ss]$ ]]
then
    # do dangerous stuff

if [ "$sender" = "me" ]; then
    sender='{"id":"'$(fyme|jq -r '.id')'"}'
else
    sender='{"phone":"'$sender'"}'
fi

if [ "$receiver" = "me" ]; then
    receiver='{"id":"'$(fyme|jq -r '.id')'"}'
else
    receiver='{"phone":"'$receiver'"}'
fi

body='{"vehicle_category":'$vehicle_category',"sections":[{"start":{"address":{"address_lines":{"0":"'$addressLine1'"},"latitude":'$latitude1',"longitude":'$longitude1'}, "player":'$sender', "dropins":[{"description":"'$description'","quantity":1,"weight":1}], "dropoffs":[]},"end":{"address":{"address_lines":{"0":"'$addressLine2'"},"latitude":'$latitude2',"longitude":'$longitude2'}, "player":'$receiver', "dropins":[],"dropoffs":[{"description":"'$description'","quantity":1,"weight":1}]},"sla":'$sla',"distance":'$distance'}]}'

#echo "creating request with body: $body"

request=$(curl -s -X POST -d "$body" "$URI/request?authorization=$FYTOKEN")

#echo $request

requestId=$(echo $request|jq -r '.request_id')
shippers=$(echo $request|jq '.shippers')

#{"id":"jk2eoNR9lBc8lhvK0PDMaHJMpGj1","nickname":"ALDO","name":"Aldo Pari","photo":"","identification_type":0,"identification_number":0,"vehicle_model":"","vehicle_domain":"","vehicle_category":0,"vehicle_photo":"","reputation":0,"route":null,"distance":-1,"commitment":3238,"presentation_photo":""}
echo "Pedido creado: $requestId"

echo "----------------"

echo "Shippers disponibles:"

while IFS= read -r shp; do
    nick=$(echo $shp|jq -r '.nickname')
    commitment=$(echo $shp|jq -r '.commitment')
    reputation=$(echo $shp|jq -r '.reputation')
    stars=""
    for i in $(seq 1 $reputation);
    do
        stars="$stars *"
    done
    commitment=$(($commitment / 60))
    echo "$nick - compromiso: $commitment mins. (reputación: $stars)"

    ##
    #photo=$(echo $shp|jq -r '.presentation_photo')
    #
    #if [ "$photo" == "" ]; then
    #    echo "No photo"
    #else
    #    echo $photo|base64 -d | jp2a --size=20x20 -
    #fi
    ##

done <<< "$(echo $shippers|jq -c '.[]')"

echo "----------------"

echo "Próximos pasos:"

echo "Monitoree el estado de su pedido: fyshow $requestId"

echo "Envíe ofertas al shipper que desee: fyoffer $requestId <shipper-nick>"

fi

