#!/usr/bin/env bash

if hash jp2a 2>/dev/null; then

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

user=$(fyuser $1|jq -r '.id')

curl -s -X GET "$URI/photos/$user/avatar?authorization=$FYTOKEN"|jq -r '.photo'|base64 -d | jp2a -

else
        echo "jp2a binary required! --> https://github.com/cslarsen/jp2a"
fi
