#!/usr/bin/env bash

API_KEY=AIzaSyB5KMSQHPEeschYJbfvDSNOl3TKLeX0-2w

echo "Refreshing token..."

REFRESH_TOKEN=$(cat $HOME/.fyrefresh)

DATA=$(curl -s 'https://securetoken.googleapis.com/v1/token?key='$API_KEY -H 'Content-Type: application/x-www-form-urlencoded' --data 'grant_type=refresh_token&refresh_token='$REFRESH_TOKEN)

export FYTOKEN=$(echo $DATA|jq -r '.id_token')
export FYREFRESH=$(echo $DATA|jq -r '.refresh_token')

echo $FYTOKEN > $HOME/.fytoken
echo $FYREFRESH > $HOME/.fyrefresh
