#!/usr/bin/env bash

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

requestId=$1

shippers=$(curl -s -X GET "$URI/request/$requestId/availability?authorization=$FYTOKEN"|jq '.shippers')

while IFS= read -r shp; do
    nick=$(echo $shp|jq -r '.nickname')
    commitment=$(echo $shp|jq -r '.commitment')
    reputation=$(echo $shp|jq -r '.reputation')
    stars=""
    for i in $(seq 1 $reputation);
    do
        stars="$stars *"
    done
    commitment=$(($commitment / 60))
    echo "$nick - compromiso: $commitment mins. (reputación: $stars)"

    ##
    #photo=$(echo $shp|jq -r '.presentation_photo')
    #
    #if [ "$photo" == "" ]; then
    #    echo "No photo"
    #else
    #    echo $photo|base64 -d | jp2a --size=20x20 -
    #fi
    ##

done <<< "$(echo $shippers|jq -c '.[]')"

echo "Próximos pasos:"

echo "Monitoree el estado de su pedido: fyshowrequest $requestId"

echo "Envíe ofertas al shipper que desee: fyoffer $requestId <shipper-nick>"

