#!/usr/bin/env bash

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

request=$(fyrequest $1|jq '.request|{created:.created,description:.description,status:.status,item:.sections[0].start.dropins[0].description}')

remaining=$(curl -s -X GET "$URI/request/$1/remaining?authorization=$FYTOKEN"|jq '.remaining')

created=$(echo $request|jq -r '.created')
description=$(echo $request|jq -r '.description')
item=$(echo $request|jq -r '.item')
status=$(echo $request|jq '.status')

case $status in
  0)
    status="Pendiente"
    ;;
  1)
    status="Esperando respuesta"
    ;;
  2)
    status="Vencido"
    ;;
  3)
    status="Aceptado"
    ;;
  4)
    status="Cancelado"
    ;;
  5)
    status="Abortado"
    ;;
esac

remaining=$(echo $request|jq '.remaining')

remaining=$(($remaining / 60))
echo '{"created":"'$created'", "description":"'$item ' - ' $description'", "status": "'$status'", "remaining":"'$remaining' mins"}'
