#!/usr/bin/env bash

#TODO print usage

URI=${API_URI:-https://api.fletaloya.com}

. fyauth

# replace spaces for + in origin & destination
address=$(echo "$1" | sed 's/\ /+/g')

address=$(curl -s -X GET "$URI/geocode?address=$address"|jq '.address')
addressLine=$(echo $address|jq '.formatted_address')
latitude=$(echo $address|jq '.latitude')
longitude=$(echo $address|jq '.longitude')

curl -s -X GET "$URI/zones/$latitude/$longitude"


